default: &default
  adapter: postgresql
  host: 127.0.0.1
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: citwitt_dev

test: &test
  <<: *default
  database: citwitt_test

production:
  database: citwitt

cucumber:
  <<: *test